PFCCLab/Camp

- Docs/03_NewIRAPI_AutoDiffAndCoreComponentRefinement/README.md
- Meetup/03_NewIRAPI_AutoDiffAndCoreComponentRefinement/README.md
- WeeklyReports/03_MarioLulab/README.md
- WeeklyReports/README.md
本 pr 对 repo 的相关内容进行了修正
1. 修复中英文标点 `:` 和 `：` 混用的问题
2. 在周报模板中添加 `导师评价` 一栏
> fix punctuation and supply weekly report template

- .github/PULL_REQUEST_TEMPLATE.md
> patch into PULL_REQUEST_TEMPLATE.md

- WeeklyReports/18_ranchongzhi/README.md
- WeeklyReports/18_ranchongzhi/[WeeklyReport]2023.10.10~2023.10.24.md
```
[WeeklyReport] USERNAME 2023.10.10~2023.10.24
```
> [WeeklyReport] ranchongzhi 2023.10.10~2023.10.24

- WeeklyReports/11_SecretXV/[WeeklyReport]2023.11.08~2023.11.21.md
> [WeeklyReport] SecretXV 2023.11.08~2023.11.21

- WeeklyReports/05_zyt1024/[WeeklyReport]2023.11.22~2023.12.05.md
```
[WeeklyReport] zyt1024 2023.11.22~2023.12.05
```
> [WeeklyReport] zyt1024 2023.11.22~2023.12.05

- WeeklyReports/Hackathon_6th/09_YibinLiu666/[WeeklyReports] 2024.02.25~2024.03.08.md
> [WeeklyReport] YibinLiu666 2024.02.25~2024.03.08

- WeeklyReports/Hackathon_6th/05_zbt78/[WeeklyReports]2024.03.09~2024.03.22.md
> [WeeklyReport] zbt78 2024.03.09~2024.03.22

- WeeklyReports/Hackathon_6th/03_zrr1999/[WeeklyReports]2024.03.09~2024.03.22.md
```
[WeeklyReport] zrr1999 2024.03.09~2024.03.22
```
> [WeeklyReport] zrr1999 2024.03.09~2024.03.22

- WeeklyReports/Hackathon_6th/04_gouzil/[WeeklyReports]2024.03.23~2024.04.05.md
> [WeeklyReport] gouzil 2024.03.23~2024.04.05

- WeeklyReports/Hackathon_6th/06_RedContritio/[WeeklyReports]2024.03.23~2024.04.05.md
> [WeeklyReport] RedContritio 2024.03.23~2024.04.05

- WeeklyReports/Hackathon_6th/03_zrr1999/[WeeklyReports]2024.03.23~2024.04.05.md
> [WeeklyReport] zrr1999 2024.03.23~2024.04.05

- WeeklyReports/Hackathon_6th/04_gouzil/[WeeklyReports]2024.04.06~2024.04.19.md
> [WeeklyReport] gouzi 2024.04.06~2024.04.19

- WeeklyReports/Hackathon_6th/18_yulangz/[WeeklyReports]2024.04.06~2024.04.19.md
> [WeeklyReports] yulangz 2024.04.06~2024.04.19

- WeeklyReports/Hackathon_6th/16_ZelinMa557/[WeeklyReport]2024.04.19~2024.05.10.md
> [WeeklyReport] ZelinMa557 2024.04.19~2024.05.10

- WeeklyReports/Hackathon_6th/18_yulangz/[WeeklyReports]2024.04.19~2024.05.10.md
[WeeklyReports] yulangz 2024.04.19~2024.05.10
> [WeeklyReports] yulangz 2024.04.19~2024.05.10

- WeeklyReports/Hackathon_6th/03_zrr1999/[WeeklyReports]2024.04.06~2024.04.19.md
> [WeeklyReport] zrr1999 add 2024.04.06~2024.04.19

- WeeklyReports/Hackathon_6th/16_ZelinMa557/[WeeklyReports]2024.05.11~2024.05.24.md
> [WeeklyReport] ZelinMa557 2024.05.11~2024.05.24

- WeeklyReports/Hackathon_6th/04_gouzil/[WeeklyReports]2024.05.11~2024.05.24.md
> [WeeklyReport] gouzil 2024.05.11~2024.05.24

- WeeklyReports/Hackathon_6th/18_yulangz/[WeeklyReports]2024.05.11~2024.05.24.md
> WeeklyReport] yulangz 202405.11~2024.05.24

- WeeklyReports/Hackathon_6th/09_YibinLiu666/[WeeklyReports]2024.05.11~2024.05.24.md
> [WeeklyReports] YibinLiu666 2024.05.11~2024.05.24

- WeeklyReports/Hackathon_6th/03_zrr1999/[WeeklyReports]2024.05.11~2024.05.24.md
> [WeeklyReport] zrr1999 2024.05.11~2024.05.24 

- WeeklyReports/Hackathon_7th/gouzil/[WeeklyReport]2024.07.15~2024.07.28.md
> [WeeklyReport] gouzil 2024.07.15~2024.07.28

- WeeklyReports/Hackathon_7th/01_ooooo-create/[WeeklyReport]2024.07.15~2024.07.28.md
> [WeeklyReport] ooooo-create 2024.07.15~2024.07.28

- WeeklyReports/Hackathon_7th/01_eggman-1024/[WeeklyReport]2024.07.15~2024.07.28.md
张瑞涛
飞桨Save/Load体系功能升级适配PIR
1. **熟悉PIR体系组件**
* 熟悉PIR体系下Program, Value, Operation等概念
2. **熟悉梳理 Paddle PIR load的逻辑**
* 理解了调用load函数后的整个反序列化流程
* 理解了jit目录下各代码文件逻辑(除engine外)
1. 理解engine目录下代码
2. 理解运行单测文件时添加的环境变量FLAGS_enable_pir_api=True在何处起作用
3. 在相关源文件中的ProgramDesc、VarDesc、FunctionInfo相关处修改代码以适配PIR体系
梳理文档补充完整后，下周可以进行pr开发
> [WeeklyReport] eggman-1024 2024.07.15~2024.07.28

- WeeklyReports/Hackathon_7th/10_Hanyonggong/[WeeklyReports]2024.07.29~2024.08.11.md
```
[WeeklyReport] Hanyonggong 2024.7.29~2024.8.11
```
> [WeeklyReport] Hanyonggong 2024.7.29~2024.8.11

- WeeklyReports/Hackathon_7th/10_gouzil/[WeeklyReport]2024.08.12~2024.08.25.md
> [WeeklyReport] gouzil 2024.08.12~2024.08.25

- WeeklyReports/Hackathon_7th/10_Hanyonggong/[WeeklyReports]2024.08.26~2024.09.08.md
```
[WeeklyReports] Hanyonggong 2024.08.26~2024.09.08
```
> [WeeklyReports] Hanyonggong 2024.08.26~2024.09.08

- WeeklyReports/Hackathon_7th/11_Xuxuanang/2024.08.26~2024.09.08.md
> [WeeklyReport] Xuxuanang 2024.08.26~2024.09.08

- WeeklyReports/Hackathon_7th/01_zrr1999/[WeeklyReport]2024.08.26~2024.09.08.md
> [WeeklyReport] zrr1999 2024.08.26~2024.09.08

- WeeklyReports/Hackathon_7th/10_layssy/[WeeklyReports]2024.08.26~2024.09.08.md
> WeeklyReport] Layssy 2024.08.26~2024.09.08

- WeeklyReports/Hackathon_7th/10_layssy/[WeeklyReports]2024.09.09~2024.09.23.md
> WeeklyReport] Layssy 2024.09.09~2024.09.23

- WeeklyReports/Hackathon_7th/01_AndPuQing/[WeeklyReport]2024.10.21~2024.10.27.md
> [WeeklyReport] AndPuQing 2024.10.21~2024.10.27

- WeeklyReports/Hackathon_7th/01_AndPuQing/[WeeklyReport]2024.08.12~2024.08.25.md
> [WeeklyReport] AndPuQing 2024.08.12~2024.08.25

- WeeklyReports/Hackathon_7th/10_Hanyonggong/[WeeklyReports]2024.09.09~2024.09.23.md
[WeeklyReport] Hanyonggong 2024.09.09~2024.09.23
> [WeeklyReport] Hanyonggong 2024.09.09~2024.09.23

- WeeklyReports/Hackathon_8th/03_smile2gmae/[WeeklyReport]2025.1.10~2025.2.16.md
刘卉杰
1. 扩展了 _reshard_mesh_shape对Partial的测试(原有Replicate)
2. 扩展了 _reshard_mesh_shape对Shard的部分_local_value不变的情况的测试，改进了_only_reshard_mesh_shape判断函数
1. 继续完善 _reshard_mesh_shape的情况
> [WeeklyReport]2025.1.10~2025.2.16

- WeeklyReports/Hackathon_8th/07_zeroRains/[WeeklyReport]2025.1.10~2025.2.16.md
> [WeeklyReport] zeroRains 2025.1.10~2025.2.16

- WeeklyReports/Hackathon_8th/06_Hanyonggong/[WeeklyReport]2025.1.10~2025.2.16.md.md
> [WeeklyReport] Hanyonggong 2025.1.10~2025.2.16

- WeeklyReports/Hackathon_8th/05_gouzil/[WeeklyReport]2025.3.3~2025.3.23.md
> [WeeklyReport] gouzil 2025.3.3~2025.3.23

- WeeklyReports/Hackathon_8th/05_gouzil/[WeeklyReport]2025.4.7~2025.4.27.md
> [WeeklyReport] gouzil 2025.4.7~2025.4.27
